var array = ["A", "B", "C", "D"];
console.log(array[1]);
console.log(array[3]);
array[2] = 3;
console.log(array);
console.log(array.length);
array.push("T");
console.log(array);
array.pop(1);
console.log(array);